import { mountUserNav } from './shared/user-nav.js'
import './pages.css'
import { apiUrl } from './shared/api.js'
const app=document.querySelector('#app');let movies=[];let favorites=new Set(JSON.parse(localStorage.getItem('cgv_favorites_v1')||'[]'))
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
app.innerHTML=`<header class="simple-header"><div class="simple-nav"><a class="simple-logo" href="/trangchu.html">CGV</a><nav><a href="/trangchu.html">Trang chủ</a><a class="active" href="/phim.html">Phim</a><a href="/lichchieu.html">Lịch chiếu</a><a href="/ve-cua-toi.html">Vé của tôi</a></nav></div></header><main class="page-wrap"><div class="page-title"><span>THƯ VIỆN ĐIỆN ẢNH</span><h1>Khám phá phim</h1><p>Tìm phim theo tên, thể loại hoặc trạng thái và lưu những phim bạn quan tâm.</p><div class="page-stats" id="stats"></div></div><div class="page-toolbar"><input id="q" placeholder="Tìm tên phim, đạo diễn, thể loại..."><select id="status"><option value="">Tất cả trạng thái</option><option value="showing">Đang chiếu</option><option value="upcoming">Sắp chiếu</option><option value="archived">Ngừng chiếu</option></select><select class="genre-filter" id="genre"><option value="">Tất cả thể loại</option></select></div><section class="catalog-grid" id="grid"></section></main>`
mountUserNav()
const $=s=>document.querySelector(s)
function saveFav(){localStorage.setItem('cgv_favorites_v1',JSON.stringify([...favorites]))}
function render(){const q=$('#q').value.trim().toLowerCase(),st=$('#status').value,g=$('#genre').value;const result=movies.filter(m=>(!q||`${m.title} ${m.director||''} ${m.genre||''}`.toLowerCase().includes(q))&&(!st||m.status===st)&&(!g||m.genre===g));$('#stats').innerHTML=`<span class="page-stat"><strong>${movies.length}</strong> phim</span><span class="page-stat"><strong>${movies.filter(m=>m.status==='showing').length}</strong> đang chiếu</span><span class="page-stat"><strong>${movies.filter(m=>m.status==='upcoming').length}</strong> sắp chiếu</span><span class="page-stat"><strong>${favorites.size}</strong> yêu thích</span>`;$('#grid').innerHTML=result.length?result.map(m=>`<article class="catalog-card"><img loading="lazy" decoding="async" src="${esc(m.poster||'/posters/poster-unavailable.svg')}" referrerpolicy="no-referrer" onerror="this.onerror=null;this.src='/posters/poster-unavailable.svg'" alt="${esc(m.title)}"><div class="catalog-body"><h2>${esc(m.title)}</h2><p>${esc(m.description||m.director||'Đang cập nhật thông tin phim.')}</p><div class="catalog-meta"><span class="tag">${esc(m.genre||'Phim')}</span><span class="tag">${esc(m.duration||'—')} phút</span><span class="tag">${esc(m.rating||'P')}</span></div><div class="catalog-actions"><a class="primary-action" href="/trangchu.html?movie=${encodeURIComponent(m.title)}#showing">${m.status==='showing'?'Đặt vé':'Xem chi tiết'}</a><button class="fav ${favorites.has(String(m.id))?'active':''}" data-fav="${esc(m.id)}">${favorites.has(String(m.id))?'★ Đã lưu':'☆ Yêu thích'}</button></div></div></article>`).join(''):`<div class="empty-page">Không tìm thấy phim phù hợp.</div>`}
async function load(){const cached=localStorage.getItem('cgv_movie_cache_v2');if(cached){try{movies=JSON.parse(cached);hydrateFilters();render()}catch{}}try{const ctl=new AbortController();setTimeout(()=>ctl.abort(),1800);const r=await fetch(apiUrl('/movies'),{signal:ctl.signal});if(!r.ok)throw 0;const fresh=await r.json();movies=fresh;localStorage.setItem('cgv_movie_cache_v2',JSON.stringify(fresh));hydrateFilters();render()}catch{if(!movies.length)render()}}
function hydrateFilters(){const current=$('#genre').value;const genres=[...new Set(movies.map(m=>m.genre).filter(Boolean))].sort();$('#genre').innerHTML='<option value="">Tất cả thể loại</option>'+genres.map(x=>`<option ${x===current?'selected':''}>${esc(x)}</option>`).join('')}
$('#q').addEventListener('input',render);$('#status').addEventListener('change',render);$('#genre').addEventListener('change',render);document.addEventListener('click',e=>{const b=e.target.closest('[data-fav]');if(!b)return;const id=b.dataset.fav;favorites.has(id)?favorites.delete(id):favorites.add(id);saveFav();render()});load()
